"""Initial migration

Revision ID: c32feaca88ae
Revises: 
Create Date: 2024-09-16 13:12:08.564847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32feaca88ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('user_host', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_audit')
    # ### end Alembic commands ###
